// This file is generated by Sharpheus. Do not edit!
#pragma once

#include "pch.h"
#include "Behavior.hpp"
#include "PlaceholderBehavior.hpp"
#include "CustomMacros.h"

// Custom behaviors
#include "CustomBehaviors/City.hpp"

#define SPH_PRESENT_BEHAVIOR(obj) \
	SPH_START_PRESENTING(obj) \
		SPH_PRESENT(PlaceholderBehavior, 0) \
		SPH_PRESENT(City, 1) \
	SPH_END_PRESENTING() \


class SPH_EXPORT BehaviorCreator
{
public:
	static Sharpheus::Behavior* Create(uint32 subType, Sharpheus::PlaceholderBehavior* other);
	static Sharpheus::Behavior* Create(uint32 subType, Sharpheus::GameObject* parent, const std::string& name);

	static bool IsCompatibleWithParent(uint32 subType, Sharpheus::GameObject* parent);

	static std::unordered_map<uint32, std::string> behaviorNames;
};

