// This file is generated by Sharpheus. Do not edit!
#include "BehaviorCreator.hpp"


const std::unordered_map<uint32_t, std::string> BehaviorCreator::behaviorNames({
	{3, "BirdCtrl"},
	{4, "CamCtrl"},
	{5, "PipeCtrl"},
	{6, "MenuCtrl"}
});


BehaviorCreator* BehaviorCreator::Instance()
{
	static BehaviorCreator instance;
	return &instance;
}


Sharpheus::Behavior* BehaviorCreator::Create(uint32_t subType, Sharpheus::PlaceholderBehavior* other)
{
	SPH_START_BEHAVIORS(subType)
		SPH_CREATE_BEHAVIOR_1(BirdCtrl, 3, other)
		SPH_CREATE_BEHAVIOR_1(CamCtrl, 4, other)
		SPH_CREATE_BEHAVIOR_1(PipeCtrl, 5, other)
		SPH_CREATE_BEHAVIOR_1(MenuCtrl, 6, other)
	SPH_END_BEHAVIOR_CREATION(subType)
}


Sharpheus::Behavior* BehaviorCreator::Create(uint32_t subType, Sharpheus::GameObject* parent, const std::string& name)
{
	SPH_START_BEHAVIORS(subType)
		SPH_CREATE_BEHAVIOR_2(Sharpheus::PlaceholderBehavior, 0, parent, name)
		SPH_CREATE_BEHAVIOR_2(Sharpheus::PythonRunnerBehavior, 1, parent, name)
		SPH_CREATE_BEHAVIOR_2(Sharpheus::PythonBehavior, 2, parent, name)
		SPH_CREATE_BEHAVIOR_2(BirdCtrl, 3, parent, name)
		SPH_CREATE_BEHAVIOR_2(CamCtrl, 4, parent, name)
		SPH_CREATE_BEHAVIOR_2(PipeCtrl, 5, parent, name)
		SPH_CREATE_BEHAVIOR_2(MenuCtrl, 6, parent, name)
	SPH_END_BEHAVIOR_CREATION(subType)
}


bool BehaviorCreator::IsCompatibleWithParent(uint32_t subType, Sharpheus::GameObject* parent)
{
	SPH_START_BEHAVIORS(subType)
		SPH_IS_BEHAVIOR_COMP(Sharpheus::PlaceholderBehavior, 0, parent)
		SPH_IS_BEHAVIOR_COMP(Sharpheus::PythonRunnerBehavior, 1, parent)
		SPH_IS_BEHAVIOR_COMP(Sharpheus::PythonBehavior, 2, parent)
		SPH_IS_BEHAVIOR_COMP(BirdCtrl, 3, parent)
		SPH_IS_BEHAVIOR_COMP(CamCtrl, 4, parent)
		SPH_IS_BEHAVIOR_COMP(PipeCtrl, 5, parent)
		SPH_IS_BEHAVIOR_COMP(MenuCtrl, 6, parent)
	SPH_END_BEHAVIOR_COMP(subType)
}

