// This file is generated by Sharpheus. Do not edit!
#include "pch.h"
#include "BehaviorCreator.hpp"


std::unordered_map<uint32_t, std::string> BehaviorCreator::behaviorNames({
	{1, "BirdCtrl"},
	{2, "CamCtrl"},
	{3, "PipeCtrl"},
	{4, "MenuCtrl"}
});


Sharpheus::Behavior* BehaviorCreator::Create(uint32_t subType, Sharpheus::PlaceholderBehavior* other)
{
	SPH_START_BEHAVIORS(subType)
		SPH_CREATE_BEHAVIOR_1(BirdCtrl, 1, other)
		SPH_CREATE_BEHAVIOR_1(CamCtrl, 2, other)
		SPH_CREATE_BEHAVIOR_1(PipeCtrl, 3, other)
		SPH_CREATE_BEHAVIOR_1(MenuCtrl, 4, other)
	SPH_END_BEHAVIOR_CREATION(subType)
}


Sharpheus::Behavior* BehaviorCreator::Create(uint32_t subType, Sharpheus::GameObject* parent, const std::string& name)
{
	SPH_START_BEHAVIORS(subType)
		SPH_CREATE_BEHAVIOR_2(Sharpheus::PlaceholderBehavior, 0, parent, name)
		SPH_CREATE_BEHAVIOR_2(BirdCtrl, 1, parent, name)
		SPH_CREATE_BEHAVIOR_2(CamCtrl, 2, parent, name)
		SPH_CREATE_BEHAVIOR_2(PipeCtrl, 3, parent, name)
		SPH_CREATE_BEHAVIOR_2(MenuCtrl, 4, parent, name)
	SPH_END_BEHAVIOR_CREATION(subType)
}


bool BehaviorCreator::IsCompatibleWithParent(uint32_t subType, Sharpheus::GameObject* parent)
{
	SPH_START_BEHAVIORS(subType)
		SPH_IS_BEHAVIOR_COMP(Sharpheus::PlaceholderBehavior, 0, parent)
		SPH_IS_BEHAVIOR_COMP(BirdCtrl, 1, parent)
		SPH_IS_BEHAVIOR_COMP(CamCtrl, 2, parent)
		SPH_IS_BEHAVIOR_COMP(PipeCtrl, 3, parent)
		SPH_IS_BEHAVIOR_COMP(MenuCtrl, 4, parent)
	SPH_END_BEHAVIOR_COMP(subType)
}

