// This file is generated by Sharpheus. Do not edit!
#pragma once

#include "pch.h"
#include "Behavior.hpp"
#include "PlaceholderBehavior.hpp"
#include "CustomMacros.h"

// Custom behaviors
#include "DebugBehavior.hpp"
#include "PlayerController.hpp"
#include "TriggerTester.hpp"
#include "MoueTester.hpp"

#define SPH_PRESENT_BEHAVIOR(obj) \
	SPH_START_PRESENTING(obj) \
		SPH_PRESENT(PlaceholderBehavior, 0) \
		SPH_PRESENT(DebugBehavior, 1) \
		SPH_PRESENT(PlayerController, 2) \
		SPH_PRESENT(TriggerTester, 3) \
		SPH_PRESENT(MoueTester, 4) \
	SPH_END_PRESENTING()


class SPH_EXPORT BehaviorCreator
{
public:
	static Sharpheus::Behavior* Create(uint32_t subType, Sharpheus::PlaceholderBehavior* other);
	static Sharpheus::Behavior* Create(uint32_t subType, Sharpheus::GameObject* parent, const std::string& name);

	static bool IsCompatibleWithParent(uint32_t subType, Sharpheus::GameObject* parent);

	static std::unordered_map<uint32_t, std::string> behaviorNames;
};

