// This file is generated by Sharpheus. Do not edit!
#pragma once

#include "pch.h"
#include "Behavior.hpp"
#include "PlaceholderBehavior.hpp"
#include "CustomMacros.h"

// Custom behaviors
#include "CustomBehaviors/PlayerController.hpp"
#include "CustomBehaviors/EnemyControl.hpp"
#include "CustomBehaviors/SpikerControl.hpp"
#include "CustomBehaviors/CamControl.hpp"
#include "CustomBehaviors/HPPackControl.hpp"
#include "CustomBehaviors/FinishControl.hpp"
#include "CustomBehaviors/MenuControl.hpp"
#include "CustomBehaviors/KeeseControl.hpp"

#define SPH_PRESENT_BEHAVIOR(obj) \
	SPH_START_PRESENTING(obj) \
		SPH_PRESENT(PlaceholderBehavior, 0) \
		SPH_PRESENT(PlayerController, 1) \
		SPH_PRESENT(EnemyControl, 2) \
		SPH_PRESENT(SpikerControl, 3) \
		SPH_PRESENT(CamControl, 4) \
		SPH_PRESENT(HPPackControl, 5) \
		SPH_PRESENT(FinishControl, 6) \
		SPH_PRESENT(MenuControl, 7) \
		SPH_PRESENT(KeeseControl, 8) \
	SPH_END_PRESENTING() \


class SPH_EXPORT BehaviorCreator
{
public:
	static Sharpheus::Behavior* Create(uint32_t subType, Sharpheus::PlaceholderBehavior* other);
	static Sharpheus::Behavior* Create(uint32_t subType, Sharpheus::GameObject* parent, const std::string& name);

	static bool IsCompatibleWithParent(uint32_t subType, Sharpheus::GameObject* parent);

	static std::unordered_map<uint32_t, std::string> behaviorNames;
};

