// This file is generated by Sharpheus. Do not edit!
#include "pch.h"
#include "BehaviorCreator.hpp"


std::unordered_map<uint32_t, std::string> BehaviorCreator::behaviorNames({
	{1, "PlayerController"},
	{2, "EnemyControl"},
	{3, "SpikerControl"},
	{4, "CamControl"},
	{5, "HPPackControl"},
	{6, "FinishControl"},
	{7, "MenuControl"},
	{8, "KeeseControl"}
});


Sharpheus::Behavior* BehaviorCreator::Create(uint32_t subType, Sharpheus::PlaceholderBehavior* other)
{
	SPH_START_BEHAVIORS(subType)
		SPH_CREATE_BEHAVIOR_1(PlayerController, 1, other)
		SPH_CREATE_BEHAVIOR_1(EnemyControl, 2, other)
		SPH_CREATE_BEHAVIOR_1(SpikerControl, 3, other)
		SPH_CREATE_BEHAVIOR_1(CamControl, 4, other)
		SPH_CREATE_BEHAVIOR_1(HPPackControl, 5, other)
		SPH_CREATE_BEHAVIOR_1(FinishControl, 6, other)
		SPH_CREATE_BEHAVIOR_1(MenuControl, 7, other)
		SPH_CREATE_BEHAVIOR_1(KeeseControl, 8, other)
	SPH_END_BEHAVIOR_CREATION(subType)
}


Sharpheus::Behavior* BehaviorCreator::Create(uint32_t subType, Sharpheus::GameObject* parent, const std::string& name)
{
	SPH_START_BEHAVIORS(subType)
		SPH_CREATE_BEHAVIOR_2(Sharpheus::PlaceholderBehavior, 0, parent, name)
		SPH_CREATE_BEHAVIOR_2(PlayerController, 1, parent, name)
		SPH_CREATE_BEHAVIOR_2(EnemyControl, 2, parent, name)
		SPH_CREATE_BEHAVIOR_2(SpikerControl, 3, parent, name)
		SPH_CREATE_BEHAVIOR_2(CamControl, 4, parent, name)
		SPH_CREATE_BEHAVIOR_2(HPPackControl, 5, parent, name)
		SPH_CREATE_BEHAVIOR_2(FinishControl, 6, parent, name)
		SPH_CREATE_BEHAVIOR_2(MenuControl, 7, parent, name)
		SPH_CREATE_BEHAVIOR_2(KeeseControl, 8, parent, name)
	SPH_END_BEHAVIOR_CREATION(subType)
}


bool BehaviorCreator::IsCompatibleWithParent(uint32_t subType, Sharpheus::GameObject* parent)
{
	SPH_START_BEHAVIORS(subType)
		SPH_IS_BEHAVIOR_COMP(Sharpheus::PlaceholderBehavior, 0, parent)
		SPH_IS_BEHAVIOR_COMP(PlayerController, 1, parent)
		SPH_IS_BEHAVIOR_COMP(EnemyControl, 2, parent)
		SPH_IS_BEHAVIOR_COMP(SpikerControl, 3, parent)
		SPH_IS_BEHAVIOR_COMP(CamControl, 4, parent)
		SPH_IS_BEHAVIOR_COMP(HPPackControl, 5, parent)
		SPH_IS_BEHAVIOR_COMP(FinishControl, 6, parent)
		SPH_IS_BEHAVIOR_COMP(MenuControl, 7, parent)
		SPH_IS_BEHAVIOR_COMP(KeeseControl, 8, parent)
	SPH_END_BEHAVIOR_COMP(subType)
}

